environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  # install node
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  # debugging info
  - node --version
  - npm --version
  # run tests
  - npm test

build: false
